config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  resources :companies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_rich_text :description

  validates :email, format: {
    with: /\b[A-Z0-9._%a-z\-]+@getmainstreet\.com\z/,
    message: "must be a getmainstreet.com domain" }

  before_save do
    zipcode_definition = ZipCodes.identify(self.zip_code)
    unless zipcode_definition.nil?
      self.city = zipcode_definition[:city]
      self.state = zipcode_definition[:state_name] + "/" + zipcode_definition[:state_code]
      # NOTE: I am storing both state codes and state names here so we can use it in any way we need.
    else
      errors.add(:zip_code, "Zipcode invalid")
      raise ActiveRecord::Rollback
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, except: [:index, :create, :new]

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def show
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path, notice: "Saved"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @company.update(company_params)
      redirect_to companies_path, notice: "Changes Saved"
    else
      render :edit
    end
  end

  def destroy
    if @company.destroy
      redirect_to companies_path, alert: "Company deleted"
    end
  end

  private

  def company_params
    params.require(:company).permit(
      :name,
      :legal_name,
      :description,
      :zip_code,
      :phone,
      :email,
      :owner_id,
    )
  end

  def set_company
    @company = Company.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
  
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/companies/_form.html.erb
<%# <%= errors_for(@company) %> %>
<div class="py-5">
  <%= form_for @company do |f| %>

    <div class="row my-lg-3">
      <div class="col-lg-3">
        <label><strong>Name</strong><br><small class="text-muted">The public DBA, or Common name of the organization</small></label>
      </div>
      <div class="col-lg offset-lg-1">
        <div class="form-group">
          <%= f.text_field :name, class: "form-control", placeholder: "Company Name", required: true %>
        </div>
      </div>
    </div>


    <div class="row my-lg-3">
      <div class="col-lg-3">
        <label><strong>Zip Code</strong><br><small class="text-muted">5 Digit US postal code</small></label>
      </div>
      <div class="col-lg offset-lg-1">
        <div class="form-group">
          <%= f.text_field :zip_code, class: "form-control", placeholder: "93003", required: true %>
        </div>
      </div>
    </div>

    <div class="row my-lg-3">
      <div class="col-lg-3">
        <label><strong>Description</strong><br><small class="text-muted">Rich text marketing description</small></label>
      </div>
      <div class="col-lg-8 offset-lg-1">
        <div class="form-group">
          <%= f.rich_text_area :description %>
        </div>
      </div>
    </div>


    <div class="row my-lg-3">
      <div class="col-lg-3">
        <label><strong>Phone</strong><br><small class="text-muted">Shown in marketing</small></label>
      </div>
      <div class="col-lg offset-lg-1">
        <div class="form-group">
          <%= f.text_field :phone, class: "form-control", placeholder: "555-555-5555"%>
        </div>
      </div>
    </div>

    <div class="row my-lg-3">
      <div class="col-lg-3">
        <label><strong>Email</strong><br><small class="text-muted">Shown in marketing</small></label>
      </div>
      <div class="col-lg offset-lg-1">
        <div class="form-group has-error">
          <%= f.text_field :email, class: @company.errors.include?(:email) ? "is-invalid form-control" : "form-control", placeholder: "hello@company.com"%>
          <small id="emailHelp" class="text-danger"><%=@company.errors.include?(:email) ? @company.errors[:email].join(', ') : ""%></small>
        </div>
      </div>
    </div>


    <div class="row my-lg-3">
      <div class="col">
        <div class="form-group">
          <%= f.submit class: "btn btn-success"%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/companies/edit.html.erb
<div class="container py-5">
  <h3>Edit Company</h3>
  <%= link_to "< Company", company_path(@company) %>
  <%= render "form" %>
</div>

app/views/companies/index.html.erb
<div class="container py-5">
  <h3>Companies</h3>
  <%= link_to "+ Create a Company", new_company_path %><br>
  <% if @companies.empty? %>
  <p>No Companies Found</p>
  <% else %>
    <ul class="list-group my-5">
      <% @companies.each do |company| %>
        <div class = "list-group-item">
          <div class = "row">
            <div class = "col-md-8">
              <a href="<%= company_path(company) %>" class="list-group-item-action">
                <%= company.name %>
              </a>
            </div>
            <div class = "col-md-4">
              <%= link_to "Delete", company_path(company), method: :delete, data: {confirm: "Are you sure ?"}, class: "float-right" %><br>
            </div>
          </div>
        </div>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/companies/new.html.erb
<div class="container py-5">
  <h3>New Company</h3>
  <%= link_to "< Companies", companies_path %>
  <%= render "form" %>
</div>

app/views/companies/show.html.erb
<div class="container py-5">
  <h3>Company</h3>
  <div class="row">
    <div class="col">
      <%= link_to "< Companies", companies_path %>
    </div>
    <div class="col text-right">
      <%= link_to "Edit", edit_company_path %>
    </div>
  </div>
  <div class="bg-success">
    <div class="container p-5 text-white">
      <h1><%= @company.name %></h1>
      <% if @company.zip_code %>
        <% if @company.city && @company.state %>
          <h3><%= "#{@company.city}, #{@company.state.split("/").last}" %></h3>
        <% else %>
          <% zipcode_definition = ZipCodes.identify(@company.zip_code) %>
          <h3><%= "#{zipcode_definition[:city]}, #{zipcode_definition[:state_code]}" %></h3>
        <% end %>
      <% end %>
      <!-- <pre>☝️ This is what needs to be udpated. Examples: Atlanta, GA or Nashvile, TN</pre> -->
    </div>
  </div>
  <% if @company.description.present? %>
    <div class="bg-light p-5">
      <%= @company.description %>
    </div>
  <% end %>
  <div class="bg-success text-white text-center py-3">
    <p class="lead"><%= @company.phone %> — <%= @company.email %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render 'shared/notices' %>
    <%= yield %>
    <div class="fixed-bottom bg-light">
    <div class="container py-3">
      <%= link_to "Home", root_path, class: "mr-5"  %>
      <%= link_to "Companies", companies_path, class: "mr-5" %>
    </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container py-5">
  <h1>Welcome 👋</h1>
  <p>Be sure you check out the REAMDE.md for specific tasks to be completed.</p>
  <p>All changes will be within <%= link_to "Companies", companies_path  %>
  <ul class="my-5 list-group">
    <li class="list-group-item">
      <h4><strong>☐ Add a way to delete companies</strong></h4>
      <p>For companies, there isn't currently a way to destroy them. There should be a confirmation of the action. Some kind of "Are you sure?" message.</p>
    </li>
    <li class="list-group-item">
      <h4><strong>☐ Add Custom Validation to company email Address (When Present)</strong></h4>
      <p>All email addresses for new companies should only be a @getmainstreet.com domain. A custom error should render when attempting to create or update a company when the email does not match this domain. This should only be when email is present. Blank emails can be ignored.</p>
    </li>
    <li class="list-group-item">
      <h4><strong>☐ Add City State To Companies from Zip Code.</strong></h4>
      <p>For each company "Show" page there is a placeholder for the <strong>City, State</strong> for that company. You'll need to leverage the zip code to have that value render the actual <strong>City, State</strong>. For example: <strong> Nashville, TN</strong> It is strongly recommended to use the <a href="https://github.com/monterail/zip-codes">ZipCodes gem</a> that is already in this project.</p>
      <p>Every time the company's zip code is updated this city and state should be updated.</p>
      <p>The City and State should be added as attributes to the Copmany object.</p>
    </li>
    <li class="list-group-item">
      <h4><strong>☐ Inlcude test coverage for all your changes</strong></h4>
      <p>For all functinality extend or add tests from existing tests.</p>
    </li>
  </ul>
</div>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>" id="alert_message"  >
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message.html_safe %>
    </div>
  </div>
<% end %>